name: Lint PHP and JS and run tests

# Trigger on push and pull request to main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install all the NPM stuff
      - name: NPM install
        shell: bash
        run: npm ci

      # Linting tings
      - name: NPM lint
        shell: bash
        run: npm run lint

      - name: NPM run prod
        shell: bash
        run: npm run prod

      # Composer install
      - name: Composer install
        shell: bash
        run: composer install

      - name: Set up Laravel
        shell: bash
        run: |
          echo "APP_KEY=$(php artisan key:generate --show)" >> .env.testing
          chmod -R 777 storage/
          php artisan route:clear

      # Do the linting
      - name: Run PHP-CS-Fixer
        shell: bash
        run: composer fix-show

      # Do some testing
      - name: Run PHP Artisan test
        shell: bash
        run: php artisan test

      - name: Show Logs
        shell: bash
        if: ${{ failure() }}
        run: cat ./storage/logs/laravel.log
